# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra", "~> 2.2", ">= 2.2.3"

gem "sinatra-contrib", "~> 2.2", ">= 2.2.3"

gem "puma", "~> 4.3", ">= 4.3.12"
